import "./globals.css";
import LayoutWrapper from "@/Component/client/Layout/LayoutWrapper";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fa" dir="rtl">
        <body className="font-estedad bg-white">
        <LayoutWrapper>
            {children}
        </LayoutWrapper>
        </body>
        </html>
    );
}
