import "./globals.css";
import LayoutWrapper from "@/Component/client/Layout/LayoutWrapper";
import Providers from "@/providers/Providers";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fa" dir="rtl">
        <body className="font-estedad bg-white">
        <Providers>
        <LayoutWrapper>
            {children}
        </LayoutWrapper>
        </Providers>
        </body>
        </html>
    );
}
